apiVersion: apps/v1
kind: Deployment
metadata:
  name: hndemo
  labels:
    app: hndemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hndemo
  template:
    metadata:
      labels:
        app: hndemo
    spec:
      containers:
        - name: hndemo
          image: gcr.io/speedscale-demos/demo-hackernews:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hndemo
spec:
  selector:
    app: hndemo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080